---
title: "Checking fish data exported from EventMeasure"
author: "Claude Spencer & Brooke Gibbons"
date: "2023-11-13"
output:
  html_vignette:
    toc: true
    code_folding: hide
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Checking fish data exported from EventMeasure}
  %\VignetteEncoding{UTF-8}
---

```{r libraries, results='hide', warning=FALSE, message=FALSE}
# Load Libraries ----
library(devtools)
library(CheckEM)
library(tidyverse)
library(googlesheets4)
library(sf)
library(terra)
```

```{r study-name}
name <- "example-bruv-workflow"
```

Skip these next 2 chunks if you have already exported metadata in the 'check-habitat' scripts
```{r load-metadata}
metadata <- read_metadata(here::here("r-workflows/data/raw/")) %>%
  dplyr::select(campaignid, sample, longitude_dd, latitude_dd, date_time, location, site, depth, successful_count, successful_length, successful_habitat_forward, successful_habitat_backward) %>%
  glimpse()
```

```{r save-metadata}
saveRDS(metadata, file = here::here(paste0("r-workflows/data/tidy/",
                                name, "_Metadata.rds")))
```

Load metadata if you have already exported in the 'check-habitat' scripts
```{r tidy-metadata}
metadata <- readRDS(here::here(paste0("r-workflows/data/tidy/",
                                name, "_Metadata.rds")))
```

```{r parks}
marine.parks <- st_read(here::here("r-workflows/data/spatial/shapefiles/Collaborative_Australian_Protected_Areas_Database_(CAPAD)_2022_-_Marine.shp"))  %>%
  dplyr::select(geometry, ZONE_TYPE) %>%
  st_transform(4326) %>%
  st_make_valid()

metadata_sf <- st_as_sf(metadata, coords = c("longitude_dd", "latitude_dd"),
                      crs = 4326)

metadata <- metadata_sf %>%
  st_intersection(marine.parks) %>%
  bind_cols(st_coordinates(.)) %>%
  as.data.frame() %>%
  dplyr::select(-c(geometry)) %>%
  dplyr::rename(longitude_dd = X, latitude_dd = Y) %>%
  dplyr::mutate(status = if_else(str_detect(ZONE_TYPE, "National|Sanctuary"),
                                "No-take", "Fished")) %>%
  clean_names() %>%
  glimpse()
```

```{r load-points}
points <- CheckEM::read_files_maxn(here::here("r-workflows/data/raw/")) %>%
  glimpse()
```

```{r create-maxn}
maxn <- points %>% 
  dplyr::group_by(campaignid, sample, filename, periodtime, frame, family, genus, species) %>% 
  dplyr::mutate(number = as.numeric(number)) %>%
  dplyr::summarise(maxn = sum(number)) %>%
  dplyr::group_by(campaignid, sample, family, genus, species) %>%
  dplyr::slice(which.max(maxn)) %>%
  dplyr::ungroup() %>%
  dplyr::filter(!is.na(maxn)) %>%
  dplyr::select(-frame) %>%
  tidyr::replace_na(list(maxn = 0)) %>%
  dplyr::mutate(maxn = as.numeric(maxn)) %>%
  dplyr::filter(maxn > 0) %>%
  dplyr::inner_join(metadata) %>%
  dplyr::filter(successful_count %in% c("Yes")) %>% 
  dplyr::filter(maxn > 0) %>%
  glimpse()
```


```{r load-lengths}
length3dpoints <- read_files_length(here::here("r-workflows/data/raw/")) %>%                   
  dplyr::select(-c(comment))%>%
  dplyr::inner_join(metadata)%>%
  dplyr::filter(successful_length %in% "Yes") %>%
  glimpse() 
```

```{r tidy-maxn}
dat <- maxn %>%
  dplyr::select(campaignid, sample, family, genus, species, maxn) %>%
  tidyr::complete(nesting(campaignid, sample), nesting(family, genus, species)) %>%
  replace_na(list(maxn = 0)) %>%
  group_by(sample, family, genus, species) %>%
  dplyr::summarise(maxn = sum(maxn)) %>%
  ungroup() %>% 
  mutate(scientific = paste(family, genus, species, sep = " "))%>%
  dplyr::select(sample, scientific, maxn)%>%
  spread(scientific, maxn, fill = 0)%>%
  glimpse()
```

```{r maxn-families}
maxn.families <- maxn %>%
  dplyr::mutate(scientific = paste(family, genus, species, sep = " ")) %>%
  filter(!(family %in% "Unknown")) %>%
  dplyr::select(c(family, genus, species, scientific)) %>%
  distinct() %>%
  glimpse()
```

```{r complete-maxn}
complete.maxn <- dat %>%
  pivot_longer(names_to = "scientific", values_to = "maxn",
               cols = 2:ncol(.)) %>%
  inner_join(maxn.families, by = c("scientific")) %>%
  full_join(metadata)%>%
  glimpse()
```

```{r complete-length}
complete.length.number <- length3dpoints %>% 
  dplyr::filter(!family %in% "Unknown")%>%
  dplyr::right_join(metadata) %>%
  dplyr::filter(successful_length %in% "Yes") %>%
  dplyr::select(campaignid, sample, family, genus, species, length, number, range) %>%
  tidyr::complete(nesting(campaignid, sample), nesting(family, genus, species)) %>%
  dplyr::mutate(number = as.numeric(number)) %>%
  replace_na(list(number = 0)) %>%
  ungroup() %>%
  dplyr::filter(!is.na(number)) %>%
  dplyr::mutate(length = as.numeric(length)) %>%
  left_join(.,metadata) %>%
  tidyr::uncount(number) %>%
  glimpse()
```

```{r save-maxn}
saveRDS(complete.maxn, 
          file = here::here(paste0("r-workflows/data/staging/",
                       name, "_complete-maxn.rds")))
```

```{r save-length}
saveRDS(complete.length.number, 
          file = here::here(paste0("r-workflows/data/staging/",
                       name, "_complete-length.rds")))
```
