---
title: "Format & visualise habitat data"
author: "Claude Spencer & Brooke Gibbons"
date: "2023-11-13"
output:
  html_vignette:
    toc: true
    code_folding: hide
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Format & visualise habitat data}
  %\VignetteEncoding{UTF-8}
---

```{r libraries, results='hide', warning=FALSE, message=FALSE}
library(CheckEM)
library(tidyverse)
library(ggbeeswarm)
library(RColorBrewer)
library(leaflet)
library(leaflet.minicharts)
library(here)
```

```{r study-name}
name <- "example-bruv-workflow"
```

```{r load-metadata}
metadata.bathy.derivatives <- readRDS(paste0("r-workflows/data/tidy/", name, "_metadata-bathymetry-derivatives.rds")) %>%
  dplyr::mutate(sample = as.character(sample)) %>%
  glimpse()
```

```{r load-habitat}
habitat <- readRDS(here::here(paste0("r-workflows/data/staging/", name, "_habitat.rds"))) %>%
  dplyr::mutate(habitat = case_when(level_2 %in% "Macroalgae" ~ level_2, level_2 %in% "Seagrasses" ~ level_2, level_2 %in% "Substrate" & level_3 %in% "Consolidated (hard)" ~ level_3, level_2 %in% "Substrate" & level_3 %in% "Unconsolidated (soft)" ~ level_3,  level_2 %in% "Sponges" ~ "Sessile invertebrates", level_2 %in% "Sessile invertebrates" ~ level_2, level_2 %in% "Bryozoa" ~ "Sessile invertebrates", level_2 %in% "Cnidaria" ~ "Sessile invertebrates")) %>% 
  dplyr::select(campaignid, sample, habitat, number) %>%
  group_by(campaignid, sample, habitat) %>% dplyr::tally(number, name = "number") %>% dplyr::mutate(total_points_annotated = sum(number)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = "habitat", values_from = "number", values_fill = 0) %>%
  dplyr::mutate(reef = Macroalgae + Seagrasses + `Sessile invertebrates` + `Consolidated (hard)`) %>%
  pivot_longer(cols = c("Macroalgae", "Seagrasses", "Sessile invertebrates", "Consolidated (hard)", "Unconsolidated (soft)", "reef"), names_to = "habitat", values_to = "number") %>%
  glimpse()
```

```{r load-relief}
tidy.relief <- readRDS(here::here(paste0("r-workflows/data/staging/", name, "_relief.rds"))) %>%
  uncount(number) %>%
  group_by(campaignid, sample) %>%
  dplyr::summarise(mean.relief = mean(as.numeric(level_5)), sd.relief = sd(as.numeric(level_5), na.rm = T)) %>%
  ungroup() %>%
  glimpse()
```

```{r format-habitat}
tidy.habitat <- metadata.bathy.derivatives %>%
  left_join(habitat) %>%
  left_join(tidy.relief) %>%
  dplyr::mutate(longitude_dd = as.numeric(longitude_dd),
                latitude_dd = as.numeric(latitude_dd)) %>%
  glimpse()
```

```{r format-relief}
plot.relief <- readRDS(here::here(paste0("r-workflows/data/staging/", name, "_relief.rds"))) %>%
  group_by(campaignid, sample, level_5) %>%
  dplyr::summarise(number = sum(number)) %>%
  ungroup() %>%
  dplyr::mutate(class.relief = as.factor(level_5)) %>%
  glimpse()
```

```{r plot-habitat}
ggplot() +
  geom_quasirandom(data = tidy.habitat, aes(x = total_points_annotated, y = habitat), groupOnX = F, method = "quasirandom", alpha = 0.25, size = 1.8, width = 0.2) +
  labs(x = "Number of points", y = "") +
  theme_classic()
```

```{r plot-relief}
ggplot() +
  geom_quasirandom(data = plot.relief, aes(x = number, y = class.relief), groupOnX = F, method = "quasirandom", alpha = 0.25, size = 1.8, width = 0.05) +
  labs(x = "Number of points", y = "Relief (0-5)") + 
  theme_classic()
```

```{r save-habitat}
saveRDS(tidy.habitat, file = here::here(paste("r-workflows/data/tidy/", paste(name,"tidy-habitat.rds", sep = "_"),sep = "/")))
```

```{r colours}
cols <- colorRampPalette(brewer.pal(12, "Paired"))(length(unique(tidy.habitat$habitat))) 
```

```{r wide-habitat}
plot.habitat <- tidy.habitat %>%
  pivot_wider(names_from = "habitat", values_from = "number", names_prefix = "broad.") %>%
  glimpse()
```

```{r pie-charts}
leaflet() %>%                                          
  addTiles(group = "Open Street Map") %>%                           
  addProviderTiles('Esri.WorldImagery', group = "World Imagery") %>%
  addLayersControl(baseGroups = c("World Imagery", "Open Street Map"), options = layersControlOptions(collapsed = FALSE)) %>%
  addMinicharts(plot.habitat$longitude_dd, plot.habitat$latitude_dd, type = "pie", colorPalette = cols, chartdata = plot.habitat[grep("broad", names(plot.habitat))], width = 20, transitionTime = 0) %>%                 
  setView(mean(as.numeric(plot.habitat$longitude_dd)), 
          mean(as.numeric(plot.habitat$latitude_dd)), zoom = 12)
```

```{r individual-habitats}
hab.name <- 'Sessile invertebrates'

overzero <-  tidy.habitat %>% 
  filter(habitat %in% hab.name & number > 0) 

equalzero <- tidy.habitat %>% 
  filter(habitat %in% hab.name & number == 0)
```

```{r bubble-plots}
bubble.plot <- leaflet(data = tidy.habitat) %>%                     
  addTiles() %>%                                                    
  addProviderTiles('Esri.WorldImagery', group = "World Imagery") %>%
  addLayersControl(baseGroups = c("Open Street Map", "World Imagery"), options = layersControlOptions(collapsed = FALSE))

if (nrow(overzero)) {                                               
  bubble.plot <- bubble.plot %>%
    addCircleMarkers(data = overzero, lat = ~ latitude_dd, lng = ~ longitude_dd, radius = ~ number + 3, fillOpacity = 0.5, stroke = FALSE, label = ~ as.character(sample))}

if (nrow(equalzero)) {                                            
  bubble.plot <- bubble.plot %>%
    addCircleMarkers(data = equalzero, lat = ~ latitude_dd, lng = ~ longitude_dd, radius = 2, fillOpacity = 0.5, color = "white", stroke = FALSE, label = ~ as.character(sample))}
bubble.plot
```