# Change log
# 2.19 (released 15/07/2025)  <br />
### Added <br />
- Added check for species out of range by using the Integrated Marine and Coastal Regionalisation of Australia (IMCRA) v4.0 - Provincial Bioregions
- Added Great Barrier Reef to the Australian marine regions
- Add IMCRA marine region shapefiles
### Updates <br/>
- Updated catami schema for habitat and CAAB codes for fish and animal species


# 2.18 (released 28/01/2025)  <br />
### Added <br />
- Added species table to MaxN (only working for EventMeasure data so far)


# 2.17 (released 13/01/2025)  <br />
### Fixed <br />
- Fixed bug not showing opcode/period when there is/are a 3D point/s and no MaxN.
- Fixed bug not showing opcode in period.wrong.length error report

# 2.16 (released 13/12/2024)  <br />
### Fixed <br />
- Fixed bug in downloading length measurements outside of transect bounds
- Fixed bug in downloading metadata points potentially on land

### Changed <br />
- Changed the default range limit from 10 m to 8 m

# 2.15 (released 10/12/2024)   <br />
### Fixed <br />
- Fixed bug in Global Life History information

## 2.14 (released 08/11/2024)  <br />
### Changed <br />
- Upcated the life history information for Australia - maximum lengths are now in Fork Length if the length-length equations are available on Fishbase

## 2.13 (released 07/11/2024)  <br />
### Added <br />
- A check for duplicated sample names
- A check for duplicated coordinates in the metadata
- A check for coordinates that are potentially on land. The shapefile used for all the countries in the world is not a high resolution, so this could be problematic for samples that are close to the coastline.
- Split the RMS checks into length measurements and 3D points.


## 2.12 (released 26/09/2023)  <br />
### Added  <br />
- A count and a length score to the QC score plot.

### Changed <br />
- Changed the calculation for the metadata score
- Changed the QC score plot to include five QC assessments.

## 2.11 (released 22/09/2023)  <br />
### Added <br />
- A PDF version of a user guide, as a download and as a window on the user guide tab.

## 2.10 (released 20/09/2023)  <br />
### Changed <br />
- Changed metadata requirements for depth, visibility, latitude and longitude to depth_m, visibility_m, latitude_dd and longitude_dd
  - If a user uploads data in the old format it will change to the new format.
- Changed generic length data column from length to length_mm
  - If a user uploads data in the old format it will change to the new format.

## 2.09 (released 18/09/2023)  <br />
### Changed <br />
- Changed from metadata having a Sample to Opcode or Period or Opcode + Period.
- Changed metadata column requirements to separated by "_"

## Added <br />
- Downloads for generic uploads.

## 2.08 (released 13/09/2023)  <br />
### Fixed <br />
- Downloads for transect based uploads.

### Changed <br />
- Only warn user if Observer.count and Observer.length are blank if Successful.count and Successful.length are not 'Yes'.
- Wording on value boxes to distinguish between EventMeasure uploads and generic uploads.

## 2.07 (released 12/09/2023)  <br />
### Added <br />
- Visibility and Inclusion Probability columns kept in the metadata.
- Loading message when data is uploading.
- Transect based methods: two different checks for samples without lengths and samples without 3D points.
- Updated Australia's life history to include other animals and a newer synonyms list.
- Updated the Global life history to include other animals and a newer synonyms list.
- Google form to update maximum lengths.
- Check for species not listed in the life history sheet.
- Columns updated merged into one pop-up.
- Percent of lengths and 3D points added to value boxes.
- RMS value box is orange if it only contains 3D points or red if contains length measurements.
- Option to keep the "Status" column uploaded in the metadata or generate one with shapefiles.
- Added new base maps to the metadata mapping for both sampling method uploads.
- Colour pallete for partially no-take areas on metadata map.
- Add all new errors to error reports.

### Fixed <br />
- Wording around transect bounds for transect based methods.
- Fixed layout of the boxes.
- Fixed "traffic light" colouring of the boxes for transect based methods.
- Fixed downloading all errors for Generic campaigns.
- Fixed downloading all errors for Transect campaigns.

## 2.06 (released 01/08/2023)  <br />
### Added <br />
- Users can now upload generic data to check, needs to be formatted in the GlobalArchive standard way
- Added new plots to investigate number of length measurements versus 3D points.

### Fixed <br />
- 3D points were being deleted in the downloads. Now kept in.

## 2.05 (released 31/07/2023)  <br />
### Added <br />
- Users can now upload metadata in the old format (e.g. separate "Date" and "Time" column) and CheckEM will turn into "Date.time" and add the timezone using the latitude and longitude columns.
- If any metadata columns are missing CheckEM will create them, but they will remain empty.

## 2.04 (released 24/07/2023) <br />
### Changed <br />
- Updated user guide for Upload, Metadata and MaxN.
- Added examples of Metadata to the user guide.

## 2.0.3 (released 14/06/2023) <br />
### Changed <br />
- Ability to check annotations against Australian or Global life history lists.
- Added Ability to use one marine region per campaignID or a marine region per sample.
  Using one per campaignID greatly improves speed.
- Added a tab to download schema for TransectMeasure and EventMeasure.
- Added ability to check habitat data.

## 2.0.2 (released 19/05/2023) <br />
### Changed <br />
- CAAB codes from EventMeasure are included in the exports.

## 2.0.1 (released 14/02/2023) <br />
### Changed <br />
- Added all Marine Parks from CAPAD 2020.
- "Fished" & "No-take" are now detected from the Zone Type in CAPAD.
- Metadata map now displays green markers for deployments inside No-take areas, and blue markers for Fished areas.

## 2.0.0 (released 31/01/2023) <br />
### Changed <br />
- Select a directory instead of manually choosing files (finds files named with "_Metadata.csv", "_Points.txt", etc.)
- One button to download all exports
- Exports are now split by campaign to allow easier uploading to GlobalArchive API
- Option to remove columns generated by CheckEM
- Metadata needs to have new "Date.time" column and "Observer.count" + "Observer.length"

### Fixed <br />
- Samples with no fish not dropped in exports with zeros.