# Change log

## 2.06 (released 01/08/2023)  <br />
### Added <br />
- Users can now upload generic data to check, needs to be formatted in the GlobalArchive standard way
- Added new plots to investigate number of length measurements versus 3D points.

### Fixed <br />
- 3D points were being deleted in the downloads. Now kept in.

## 2.05 (released 31/07/2023)  <br />
### Added <br />
- Users can now upload metadata in the old format (e.g. separate "Date" and "Time" column) and CheckEM will turn into "Date.time" and add the timezone using the latitude and longitude columns.
- If any metadata columns are missing CheckEM will create them, but they will remain empty.

## 2.04 (released 24/07/2023) <br />
### Changed <br />
- Updated user guid for Upload, Metadata and MaxN.
- Added examples of Metadata to the user guide.

## 2.0.3 (released 14/06/2023) <br />
### Changed <br />
- Ability to check annotations against Australian or Global life history lists.
- Added Ability to use one marine region per campaignID or a marine region per sample.
  Using one per campaignID greatly improves speed.
- Added a tab to download schema for TransectMeasure and EventMeasure.
- Added ability to check habitat data.

## 2.0.2 (released 19/05/2023) <br />
### Changed <br />
- CAAB codes from EventMeasure are included in the exports.

## 2.0.1 (released 14/02/2023) <br />
### Changed <br />
- Added all Marine Parks from CAPAD 2020.
- "Fished" & "No-take" are now detected from the Zone Type in CAPAD.
- Metadata map now displays green markers for deployments inside No-take areas, and blue markers for Fished areas.

## 2.0.0 (released 31/01/2023) <br />
### Changed <br />
- Select a directory instead of manually choosing files (finds files named with "_Metadata.csv", "_Points.txt", etc.)
- One button to download all exports
- Exports are now split by campaign to allow easier uploading to GlobalArchive API
- Option to remove columns generated by CheckEM
- Metadata needs to have new "Date.time" column and "Observer.count" + "Observer.length"

### Fixed <br />
- Samples with no fish not dropped in exports with zeros.